# Tables {#sec-tables}
 
```{r}
#| label: tbl-no-format
#| tbl-cap: "This is a basic caption for the table without formatting."
#| echo: false
cars |>
gt::gt()
```

```{r}
#| label: tbl-format-gt
#| tbl-cap: "This is a basic caption for the table with formatting."
#| echo: false
cars |>
gt::gt() |>
gt::tab_options(
            table.font.size = "10",
            latex.use_longtable = TRUE,
            latex.header_repeat = TRUE
        ) |>
        # bold column labels
        gt::tab_style(
            style = gt::cell_text(weight = "bold"),
            locations = gt::cells_column_labels()
        )
```

```{r}
#| label: tbl-no-format-kbl
#| tbl-cap: "This is a basic caption for the table without formatting for a kable table."
#| echo: false
cars |>
kableExtra::kable()
```

```{r}
#| label: tbl-format-kbl
#| tbl-cap: "This is a basic caption for the table with formatting for a kable table."
#| echo: false
cars |>
kableExtra::kable() |>
kableExtra::kable_styling(
  font_size = 10,
  latex_options = c("repeat_header")
)
```
